#!/bin/sh
set -e
PREREQS=""
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

rootimg_path=/run/initramfs/root.img
# shellcheck disable=SC2013
for x in $(cat /proc/cmdline); do
  case $x in
  root_sha256=*) root_sha256=${x#root_sha256=} ;;
  esac
done
if [ -z "${root_sha256}" ]; then
  panic "Unable to mount root disk. Boot argument root_sha256= not specified"
  exit 1
fi

verify_rootimg() {
  log_begin_msg "Verifying checksum of root.img"
  if printf "%s  %s" "$root_sha256" $rootimg_path.tmp | sha256sum -c -; then
    boot_state=$(jq --arg rootimg_sha256 "$root_sha256" '.rootimg_sha256=$rootimg_sha256' /run/initramfs/boot-state.json)
    printf "%s\n" "$boot_state" >/run/initramfs/boot-state.json
    mv $rootimg_path.tmp $rootimg_path
  else
    panic "root.img checksum is incorrect"
    exit 1
  fi
}

esp=/run/initramfs/efi
if [ -e $esp/home-cluster/root.img ]; then
  log_begin_msg "Copying root.img from ESP to RAM"
  if cp $esp/home-cluster/root.img $rootimg_path.tmp; then
    boot_state=$(jq '.rootimg_src="ESP"' /run/initramfs/boot-state.json)
    printf "%s\n" "$boot_state" >/run/initramfs/boot-state.json
    log_end_msg
    verify_rootimg
    exit 0
  else
    log_failure_msg "Failed to copy root.img, falling back to downloading from boot-server"
  fi
  # Try to download root.img instead, the sha256 might not match though
fi
set +e; configure_networking; set -e
if [ -n "$ROOTSERVER" ]; then
  img_addr=http://${ROOTSERVER}/$(uname -m)/root.img
  log_begin_msg "Downloading root image to RAM from $img_addr"
  if curl -fsL --connect-timeout 5 --retry 3 -o $rootimg_path.tmp "$img_addr"; then
    boot_state=$(jq '.rootimg_src="boot-server"' /run/initramfs/boot-state.json)
    printf "%s\n" "$boot_state" >/run/initramfs/boot-state.json
    log_end_msg
    verify_rootimg
    exit 0
  else
    panic "Failed to download root.img: Download failed"
    exit 1
  fi
else
  panic "Failed to download root.img: ROOTSERVER/NEXT_SERVER not found in DHCP lease"
  exit 1
fi
