#!/usr/bin/env bash
set -Eeo pipefail; shopt -s inherit_errexit
[[ $1 != prereqs ]] || { echo ""; exit 0; }

# shellcheck disable=SC1091
source /scripts/functions
PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
# shellcheck source=../common.sh
source "$PKGROOT/common.sh"

ROOT_BASENAME=${ROOT#'/run/initramfs/'}

if [[ $ROOT_BASENAME =~ ^root.([0-9a-f]{64}).img$ ]]; then
  ROOT_SHA256=${BASH_REMATCH[1]}
  set_node_state rootimg.sha256 "$ROOT_SHA256"
else
  panic "root= argument is not of the form root.<sha256>.img, unable to continue"
  exit 1
fi

verify_rootimg() {
  info "Verifying checksum of root.img"
  if printf "%s  %s" "$ROOT_SHA256" "$ROOT.tmp" | sha256sum -c -; then
    set_node_state rootimg.sha256 "$ROOT_SHA256"
    mv "$ROOT.tmp" "$ROOT"
  else
    error "root.img checksum is incorrect"
    return 1
  fi
}

main() {
  local rootimg_src_path=/run/initramfs/boot/home-cluster/$ROOT_BASENAME
  if [[ -e $rootimg_src_path ]]; then
    info "Copying root.img from boot partition to RAM"
    if cp "$rootimg_src_path" "$ROOT.tmp"; then
      set_node_state rootimg.src "$rootimg_src_path"
      if verify_rootimg; then
        return 0
      else
        info "Falling back to downloading root.img from boot-server"
      fi
    else
      error "Failed to copy root.img, falling back to downloading from boot-server"
      # Try to download root.img instead, the sha256 might not match though
    fi
  fi

  local boot_server rootimg_src_addr
  if boot_server=$(get_node_state boot-server); then
    VARIANT=$(get_node_state variant)
    rootimg_src_addr=https://${boot_server}:8020/images/${VARIANT}/$ROOT_BASENAME
    info "Downloading root image to RAM from $rootimg_src_addr"
    if curl_boot_server -o"$ROOT.tmp" "$rootimg_src_addr"; then
      set_node_state rootimg.src "$rootimg_src_addr"
      if ! verify_rootimg; then
        panic "Unable to continue"
      else
        return 0
      fi
    else
      panic "Failed to download root.img: Download failed"
      return 1
    fi
  else
    panic "Failed to download root.img: boot-server not present in node-state.json"
    return 1
  fi
}

main "$@"
