#!/usr/bin/env bash
# shellcheck disable=SC2086

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD usermod -L root
# enable sudo for admin
ainsl /etc/sudoers "${ADMIN_USERNAME:?}   ALL = ALL"
[ -f "${target:?}/usr/bin/sudo" ] || echo "WARNING. Package sudo is not installed"
$ROOTCMD useradd -m -s ${ADMIN_USER_SHELL:?} -u "${ADMIN_UID:?}" "$ADMIN_USERNAME"
$ROOTCMD usermod -p "${ADMIN_PASSWORD:?}" "$ADMIN_USERNAME"
userdir=$($ROOTCMD getent passwd "$ADMIN_USERNAME" | cut -d: -f6 )
$ROOTCMD mkdir "$userdir/.ssh"
[[ -z $ADMIN_AUTH_KEYS ]] || ainsl -a "$userdir/.ssh/authorized_keys" "$ADMIN_AUTH_KEYS"
$ROOTCMD chown -R "$ADMIN_USERNAME:$ADMIN_USERNAME" "$userdir/.ssh"
$ROOTCMD chmod -R u=rwX,go=rX "$userdir/.ssh"
[[ -z $ADMIN_NFS_HOME_SHARE ]] || ainsl -a /etc/fstab "${NFS_NODE_SERVER_IP}:${ADMIN_NFS_HOME_SHARE}    /home/${ADMIN_USERNAME}/    nfs    defaults    0 0"

exit $error
