#!/bin/sh
################################################################################
# Don't use any bash variables in this file ("$VAR" or "${VAR}").
# It is rendered with `envsubst` in order to inline "${VARIANT}"
################################################################################

set -e
case $1 in
	prereqs) echo ""; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

printf '{"variant": "%s"}' "${VARIANT}" >/run/initramfs/boot-state.json
