#!/bin/sh
set -e
# We need udev to create the by-uuid links
PREREQS=""
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

printf "{}" >/run/initramfs/boot-state.json
