#!/usr/bin/env bash
set -Eeo pipefail; shopt -s inherit_errexit
[[ $1 != prereqs ]] || { echo "create-node-state"; exit 0; }

PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
# shellcheck source=../common.sh
source "$PKGROOT/common.sh"
# shellcheck source=../disk-uuids.sh
source "$PKGROOT/disk-uuids.sh"

main() {
  local boot_devpath
  if boot_devpath=/dev/$(lsblk -Jno NAME,PTUUID,PARTUUID -a | jq -re --arg disk_uuid "$DISK_UUID" --arg part_uuid "$ESP_UUID" \
    '[.blockdevices[] | select(.ptuuid==$disk_uuid) | .children[] | select(.partuuid=$part_uuid) | .name] | first'); then
    info "Mounting boot partition"
    boot_path=/run/initramfs/boot-disk
    mkdir $boot_path
    if mount -rt vfat "$boot_devpath" $boot_path; then
      rm -rf "$boot_path"
      error "Failed to mount boot partition"
    fi
  else
    warning "boot partition not found, skipping mounting of /run/initramfs/boot-disk"
  fi
}

main "$@"
