#!/bin/sh
set -e
# We need udev to create the by-uuid links
PREREQS="udev create-boot-state"
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

DISK_UUID=caf66bff-edab-4fb1-8ad9-e570be5415d7
ESP_UUID=c12a7328-f81f-11d2-ba4b-00a0c93ec93b
if [ -e /dev/disk/by-partuuid/$ESP_UUID ]; then
  device=/dev/$(basename "$(readlink /dev/disk/by-partuuid/$ESP_UUID)" 1)
  if [ "$(blkid -s PTUUID -o value "$device")" != $DISK_UUID ]; then
    log_failure_msg "The disk $device does not have the expected UUID of $DISK_UUID, aborting."
    exit 1
  fi
  log_begin_msg "ESP detected on $device, mounting"
  esp_path=/run/initramfs/efi
  mkdir $esp_path
  mount -rt vfat /dev/disk/by-partuuid/$ESP_UUID $esp_path
  log_end_msg
  boot_state=$(jq --arg esp_devpath "$device" '.esp_devpath=$esp_devpath' /run/initramfs/boot-state.json)
  printf "%s\n" "$boot_state" >/run/initramfs/boot-state.json
fi
