#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# shellcheck disable=2054
k3s_exec_flags=(
  --flannel-backend=none
  --egress-selector-mode=disabled
  --disable=traefik
  --disable=metrics-server
  --disable=servicelb
  --disable-network-policy
  --disable-kube-proxy
  --disable-helm-controller
  "--kube-controller-manager-arg=node-cidr-mask-size-ipv4=${CLUSTER_IPV4_CIDR##*/}"
  "--kube-controller-manager-arg=node-cidr-mask-size-ipv6=${CLUSTER_IPV6_CIDR##*/}"
  "--cluster-cidr=${CLUSTER_IPV4_CIDR},${CLUSTER_IPV6_CIDR}"
  "--service-cidr=${CLUSTER_IPV4_SERVICE_CIDR},${CLUSTER_IPV6_SERVICE_CIDR}"
)

curl -sfL https://get.k3s.io | \
  INSTALL_K3S_SKIP_START=true \
  INSTALL_K3S_EXEC="${k3s_exec_flags[*]}" \
  $ROOTCMD sh -

fcopy -SM /etc/systemd/system/adjust-kubeconf-perms.service
$ROOTCMD systemctl enable adjust-kubeconf-perms.service

exit $error
