#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ainsl -a /etc/fstab ""
ainsl -a /etc/fstab "# NFS mount for rancher, it writes k8s secrets to this dir"
ainsl -a /etc/fstab "${NFS_NODE_SERVER_IP:?}:${NFS_NODE_SHARE:?}/${HOSTNAME}/etc/rancher    /etc/rancher    nfs    defaults    0 0"
ainsl -a /var/lib/fai/nfs-mounts "/etc/rancher"
mkdir "${target:?}/etc/rancher"

exit $error
