#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -BSM /etc/hostname
fcopy -BSM /etc/machine-id
fcopy -BSM /var/lib/dbus/machine-id

exit $error
