#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

rm "${target:?}/etc/locale.gen"
$ROOTCMD dpkg-reconfigure --frontend noninteractive locales

exit $error
