#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD systemctl disable apt-daily.timer
$ROOTCMD systemctl disable apt-daily-upgrade.timer
$ROOTCMD systemctl mask apt-daily.service

exit $error
