#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

for mountpath in /var/lib/systemd /var/log/journal; do
  ainsl -a /etc/fstab "${NFS_NODE_SERVER_IP:?}:${NFS_NODE_SHARE:?}/${HOSTNAME}/${mountpath#/}    ${mountpath}    nfs    defaults    0 0"
  ainsl -a /var/lib/fai/nfs-mounts "$mountpath"
done

exit $error
