#!/usr/bin/env bash
# shellcheck source-path=../../..
set -Eeo pipefail; shopt -s inherit_errexit
PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../../..")

main() {
  source "$PKGROOT/lib/common.sh"
  source "$PKGROOT/workloads/auth/lib/auth.sh"
  local cert_path key_path
  cert_path=$(get_client_crt_path "$STEP_KUBE_API_CONTEXT")
  key_path=$(get_client_key_path "$STEP_KUBE_API_CONTEXT")
  case "$1" in
    get)
      registry=$(cat)
      username=$(step certificate inspect "$cert_path" --format json | jq -r '.subject.common_name[0]')
      username=${username//:/'/'} # No way to include colon in basic auth username
      sig=$(step crypto jws sign --x5c-cert "$cert_path" --key="$key_path")
      jq -c --arg ServerURL "$registry" --arg Username "$username" --arg Secret "$sig" \
        '{ServerURL: $ServerURL, Username: $Username, Secret: $Secret}' <<<'{}' | tee -a /tmp/docker-creds
      ;;
    list)
      username=$(step certificate inspect "$cert_path" --format json | jq -r '.subject.common_name[0]')
      jq -c --arg username "$username" '[{key: "cr.example.org", value: $username}] | from_entries' <<<'{}'
      ;;
    version)
      printf "docker-credential-home-cluster (github.com/andsens/home-cluster) v1.0.0\n"
      ;;
    *) return 0 ;;
  esac
}

main "$@"
