#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# shellcheck disable=2054
k3s_exec_flags=(
  --flannel-backend=none
  --egress-selector-mode=disabled
  --disable=traefik
  --disable=metrics-server
  --disable=servicelb
  --disable-network-policy
  --disable-kube-proxy
  --disable-helm-controller
  "--kube-controller-manager-arg=node-cidr-mask-size-ipv4=24"
  "--kube-controller-manager-arg=node-cidr-mask-size-ipv6=112"
  "--cluster-cidr=${CLUSTER_IPV4_POD_CIDR},${CLUSTER_IPV6_POD_CIDR}"
  "--service-cidr=${CLUSTER_IPV4_SVC_CIDR},${CLUSTER_IPV6_SVC_CIDR}"
  "--kube-apiserver-arg=client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca-bundle.crt"
)

curl -sfL https://get.k3s.io | \
  INSTALL_K3S_SKIP_START=true \
  INSTALL_K3S_EXEC="${k3s_exec_flags[*]}" \
  $ROOTCMD sh -

fcopy -SM /etc/systemd/system/link-k3s-data.service
$ROOTCMD systemctl enable link-k3s-data.service

exit $error
