#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -SM /etc/systemd/system/setup-cluster-dns.service
$ROOTCMD systemctl enable setup-cluster-dns.service

exit $error
