#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

wget -qO- https://dl.smallstep.com/gh-release/cli/gh-release-header/v0.26.0/step_linux_0.26.0_amd64.tar.gz | \
  tar xzC "${target:?}/usr/local/bin" --strip-components 2 step_0.26.0/bin/step
chmod +x "${target:?}/usr/local/bin/step"

for unit in sign-ssh-host-keys.service sign-ssh-host-keys.timer download-ssh-user-ca-keys.service; do
  fcopy -SM /etc/systemd/system/$unit.timer
  $ROOTCMD systemctl enable $unit.service
done

fcopy -M /etc/ssh/sshd_config.d/20-host-key-certs.conf
fcopy -M /etc/ssh/sshd_config.d/30-user-ca-keys.conf

exit $error
