---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: image-registry
  labels:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: image-registry
      app.kubernetes.io/component: image-registry
  ingress:
  - toPorts:
    - ports:
      - port: "8020"
    fromEntities:
    - host
    - remote-node
    - cluster
  - toPorts:
    - ports:
      - port: "8020"
    fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: image-registry
        app.kubernetes.io/component: image-registry
  - toPorts:
    - ports:
      - port: "8021"
    fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: bootstrap
  egress:
  - toPorts:
    - ports:
      - port: "8020"
    toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: image-registry
        app.kubernetes.io/component: image-registry
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  labels:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
  ports:
  - name: image-registry
    port: 8020
    targetPort: images
  - name: image-registry-mgmt
    port: 8021
    targetPort: dav
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry-headless
  labels:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-registry
  labels:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
spec:
  commonName: image-registry.phxc.svc.cluster.local
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: kube-server
  secretName: image-registry-tls
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-registry
  labels:
    app.kubernetes.io/name: image-registry
    app.kubernetes.io/component: image-registry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: image-registry
      app.kubernetes.io/component: image-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image-registry
        app.kubernetes.io/component: image-registry
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      initContainers:
      - name: chown-images
        image: busybox:1.37.0
        args: [chown, 101:101, /var/lib/phxc/images]
        volumeMounts:
        - name: images
          mountPath: /var/lib/phxc/images
      containers:
      - name: image-registry
        image: nginx:1.27.3
        args: [/scripts/reload-nginx.sh, nginx, -c, /etc/nginx/nginx-conf/nginx.conf]
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: images
          containerPort: 8020
        - name: dav
          containerPort: 8021
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: config
          mountPath: /etc/nginx/nginx-conf
        - name: image-registry-tls
          mountPath: /etc/nginx/tls
        - name: images
          mountPath: /var/lib/phxc/images
        - name: nginx-cache
          mountPath: /var/cache/nginx
      - name: image-sync
        image: ghcr.io/andsens/phxc-utils
        command: [/scripts/sync-images.sh]
        args: [amd64, arm64, rpi5]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: images
          mountPath: /var/lib/phxc/images
      volumes:
      - name: config
        configMap:
          name: image-registry-config
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0755
      - name: images
        hostPath:
          path: /var/lib/phxc/images
          type: DirectoryOrCreate
      - name: image-registry-tls
        secret:
          secretName: image-registry-tls
      - name: nginx-cache
        emptyDir: {}
