apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phxc
images:
- name: ghcr.io/andsens/phxc-utils
  newTag: sha-3d836db
resources:
- image-registry.yaml
configMapGenerator:
- files:
  - config/nginx.conf
  name: image-registry-config
- files:
  - scripts/reload-nginx.sh
  - scripts/sync-images.sh
  name: scripts
generatorOptions:
  disableNameSuffixHash: true
