#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if ifclass K8SNODE || ifclass K8SMASTER; then
  wget -qO- "https://dl.smallstep.com/gh-release/cli/gh-release-header/v0.26.0/step_linux_0.26.0_${arch_suffix:?}.tar.gz" | \
    tar xzC "${target:?}/usr/local/bin" --strip-components 2 step_0.26.0/bin/step
  chmod +x "${target:?}/usr/local/bin/step"

  for unit in download-ssh-user-ca-keys.service sign-ssh-host-keys.service sign-ssh-host-keys.timer; do
    fcopy -SM /etc/systemd/system/$unit
    $ROOTCMD systemctl enable $unit
  done

  fcopy -M /etc/ssh/sshd_config.d/20-host-key-certs.conf
  fcopy -M /etc/ssh/sshd_config.d/30-user-ca-keys.conf
fi

exit $error
