#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

mkdir "${target:?}/var/lib/k8s-master"
ln -s /var/lib/k8s-master/lib-rancher "${target:?}/var/lib/rancher"
ln -s /var/lib/k8s-master/lib-kubelet "${target:?}/var/lib/kubelet"

fcopy -SM /etc/systemd/system/expand-var.service
fcopy -SM "/etc/systemd/system/var-lib-k8s\x2dmaster.mount"
$ROOTCMD systemctl enable expand-var.service
$ROOTCMD systemctl enable 'var-lib-k8s\x2dmaster.mount'

exit $error
