#!/bin/sh

# We don't have any prerequirements
PREREQS=""
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/blkid /bin
