#!/usr/bin/env bash
# shellcheck disable=SC2086

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD usermod -L root
# enable sudo for admin
ainsl /etc/sudoers "${ADMIN_USERNAME:?}   ALL = ALL"
[ -f "${target:?}/usr/bin/sudo" ] || echo "WARNING. Package sudo is not installed"
$ROOTCMD useradd -m -s "$ADMIN_SHELL" -u "$ADMIN_UID" "$ADMIN_USERNAME"
[[ -z $ADMIN_PW_HASH ]] || $ROOTCMD usermod -p "$ADMIN_PW_HASH" "$ADMIN_USERNAME"
$ROOTCMD adduser $ADMIN_USERNAME adm
userdir=$($ROOTCMD getent passwd "$ADMIN_USERNAME" | cut -d: -f6 )
$ROOTCMD mkdir "$userdir/.ssh"

[[ -z $ADMIN_AUTH_KEYS ]] || ainsl -a "$userdir/.ssh/authorized_keys" "$ADMIN_AUTH_KEYS"

$ROOTCMD chown -R "$ADMIN_USERNAME:$ADMIN_USERNAME" "$userdir/.ssh"
$ROOTCMD chmod -R u=rwX,go=rX "$userdir/.ssh"

if [[ -n $NFS_SHARES_ADMIN_HOME_ADDR ]]; then
  systemd_unitname=$(systemd-escape -p --suffix=mount "/home/${ADMIN_USERNAME}")
  cat >"${target:?}/etc/systemd/system/${systemd_unitname}" <<EOF
[Unit]
Description=Mount /home/${ADMIN_USERNAME}
After=network-online.target

[Install]
WantedBy=multi-user.target

[Mount]
What=${NFS_SHARES_ADMIN_HOME_ADDR}:${NFS_SHARES_ADMIN_HOME_PATH}
Where=/home/${ADMIN_USERNAME}
Type=nfs
EOF
  $ROOTCMD systemctl enable "${systemd_unitname}"
fi

exit $error
