apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../lib/cluster-settings
- pool.yaml
- bgpp.yaml
- ready-checks.yaml
replacements:
- source: {fieldPath: data.cidrs.lb.ipv4, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: cilium.io, kind: CiliumLoadBalancerIPPool, name: lan-addresses}
    fieldPaths: [spec.blocks.0.cidr]
- source: {fieldPath: data.cidrs.lb.ipv6, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: cilium.io, kind: CiliumLoadBalancerIPPool, name: lan-addresses}
    fieldPaths: [spec.blocks.1.cidr]
- source: {fieldPath: data.bgp.router.ipv4, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: cilium.io, kind: CiliumBGPPeeringPolicy, name: router}
    fieldPaths: [spec.virtualRouters.0.neighbors.0.peerAddress]
    options: {delimiter: '/', index: 0}
- source: {fieldPath: data.bgp.router.ipv6, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: cilium.io, kind: CiliumBGPPeeringPolicy, name: router}
    fieldPaths: [spec.virtualRouters.0.neighbors.1.peerAddress]
    options: {delimiter: '/', index: 0}
