#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if [[ -z $(find "${target:?}/boot" -name 'vmlinu*') ]]; then
  echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
  error=1
fi

exit $error
