#!/bin/sh

# We don't have any prerequirements
PREREQS=""
case $1 in
  prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/blkid /bin
copy_exec /usr/bin/curl /bin
copy_exec /usr/bin/jq /bin
copy_exec /usr/bin/basename /bin
copy_exec /usr/bin/readlink /bin
copy_exec /usr/bin/cp /bin
copy_exec /usr/bin/bash /bin
