#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Install last so dns resolution works during bootstrapping
$ROOTCMD apt-get install --no-install-recommends -y systemd-resolved

exit $error
