#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -M /etc/ssh/sshd_config.d/50-tmux.conf

rm "${target:?}/etc/ssh/ssh_host_"*
fcopy -SM /etc/systemd/system/generate-ssh-host-keys.service
$ROOTCMD systemctl enable generate-ssh-host-keys.service

exit $error
