apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
images:
- name: ghcr.io/andsens/phxc-coredns
  newTag: sha-6f1e1cf
- name: ghcr.io/andsens/phxc-utils
  newTag: sha-3d836db
resources:
- ../../lib/cluster-settings
- coredns.yaml
generators:
- generate-kube-dns-ip.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata: {name: kube-dns-ip, annotations: {config.kubernetes.io/local-config: "true"}}
configMapGenerator:
- files:
  - config/Corefile
  name: coredns
- files:
  - scripts/render-imports.sh
  name: scripts
replacements:
- source: {fieldPath: data.domain, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {kind: Service, name: external-coredns}
    fieldPaths: [metadata.annotations.coredns\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: Deployment, name: coredns}
    fieldPaths: ["spec.template.spec.containers.[name=coredns].env.[name=CLUSTER_DOMAIN].value"]
- source: {fieldPath: data.ipv4, kind: ConfigMap, name: kube-dns-ip}
  targets:
  - select: {kind: Service, name: kube-dns}
    fieldPaths: [spec.clusterIP]
  - select: {kind: Service, name: kube-dns}
    fieldPaths: [spec.clusterIPs.0]
- source: {fieldPath: data.ipv6, kind: ConfigMap, name: kube-dns-ip}
  targets:
  - select: {kind: Service, name: kube-dns}
    fieldPaths: [spec.clusterIPs.1]
