#!/bin/sh
set -e
PREREQS=""
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

dl_failed=false

# shellcheck disable=SC2013
for x in $(cat /proc/cmdline); do
  case $x in
  bootserver=*)
    bootserver=${x#bootserver=}
    ;;
  esac
done

rootimg_path=/run/initramfs/root.img
if [ -z "${bootserver}" ]; then
  log_warning_msg "Skipping download of root image. Boot argument bootserver= not specified"
  dl_failed=true
else
  set +e; configure_networking; set -e
  if ( wget -qOtest "http://${bootserver}/" & w=$!; sleep .5; kill -0 $w 2>/dev/null || exit 0; kill -TERM $w; exit 1 ); then
    img_addr=http://${bootserver}/$(uname -m)/root.img
    log_begin_msg "Downloading root image to RAM from $img_addr"
    if ! wget -qO$rootimg_path "$img_addr"; then
      log_failure_msg "Failed downloading root.img"
      dl_failed=true
    else
      log_end_msg
      exit 0
    fi
  else
    log_failure_msg "Bootserver is unavailable"
    dl_failed=true
  fi
fi

if $dl_failed; then
  esp=/run/initramfs/efi
  if [ -e $esp/home-cluster/latest/root.img ]; then
    log_begin_msg "Falling back to copying root.img from ESP to RAM"
    if cp "$esp/home-cluster/latest/root.img" $rootimg_path; then
      log_end_msg
      exit 0
    fi
    log_failure_msg "Failed to copy root.img"
  fi
fi

exit 1
