#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

for unit in bootstrap.target var-lib-persistent-images.mount bootstrap.service; do
  fcopy -SM "/etc/systemd/system/$unit"
  $ROOTCMD systemctl enable "$unit"
done

exit $error
