#!/bin/sh
set -e
# Download the settings first and make sure we can write to the fstab
PREREQS="settings overlayroot"
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

settings_path=/run/initramfs/node-settings.json
if [ ! -e "$settings_path" ]; then
  log_warning_msg "Skipping persistent disk setup. $settings_path does not exist"
  exit 0
fi
hostname=$(jq -r '.hostname // "node"' "$settings_path")

if ! persistentdev=$(jq -re '.data' "$settings_path"); then
  log_failure_msg "$hostname has no data device defined, skipping"
  exit 0
fi

# https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html#x-systemd.makefs
# The mkfs and growfs options are not available when specifying this mount as a systemd mount unit, so we use fstab
# shellcheck disable=SC2154
printf "%s  /var/lib/persistent  ext4  defaults,x-systemd.makefs,x-systemd.growfs\n" "$persistentdev" >>"$rootmnt/etc/fstab"
log_success_msg "Set up $persistentdev as persistent disk"
