#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

debconf-set-selections <<<"tzdata tzdata/Areas select Europe
tzdata tzdata/Zones/Europe select Copenhagen
locales locales/locales_to_be_generated multiselect     en_US.UTF-8 UTF-8
locales locales/default_environment_locale      select  en_US.UTF-8
ucf ucf/changeprompt select keep_current"

# busybox is needed by scripts in initramfs
apt-install systemd busybox locales curl

rm /etc/locale.gen
dpkg-reconfigure --frontend noninteractive locales tzdata

systemctl disable apt-daily.timer
systemctl disable apt-daily-upgrade.timer
systemctl mask apt-daily.service

cp-tpl /etc/systemd/system/var-lib-home\\x2dcluster.mount
systemctl enable var-lib-home\\x2dcluster.mount
