#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

apt-install sudo "$(basename "${ADMIN_SHELL:?}")"
usermod -L root
useradd -m -s "$ADMIN_SHELL" -u "${ADMIN_UID:?}" "${ADMIN_USERNAME:?}"
usermod -p "${ADMIN_PWHASH:?}" "$ADMIN_USERNAME"
adduser "$ADMIN_USERNAME" adm
adduser "$ADMIN_USERNAME" sudo
userdir=$(getent passwd "$ADMIN_USERNAME" | cut -d: -f6 )

mkdir "$userdir/.ssh"
[[ -z $ADMIN_AUTH_KEYS ]] || ainsl -a "$userdir/.ssh/authorized_keys" "$ADMIN_AUTH_KEYS"
chown -R "$ADMIN_USERNAME:$ADMIN_USERNAME" "$userdir/.ssh"
chmod -R u=rwX,go=rX "$userdir/.ssh"

if [[ -n $NFS_SHARES_ADMIN_HOME_ADDR ]]; then
  systemd_unitname=$(systemd-escape -p --suffix=mount "/home/$ADMIN_USERNAME")
  cp-tpl /etc/systemd/system/admin-home.mount -d "/etc/systemd/system/$systemd_unitname"
  systemctl enable "$systemd_unitname"
fi
