#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

apt-install nbd-client
printf "squashfs\n" >>/etc/initramfs-tools/modules
