#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

apt-install \
  systemd-resolved \
  avahi-daemon libnss-mdns wget ca-certificates nfs-common
systemctl enable systemd-networkd

cp-tpl /etc/systemd/network/lan0.network

cp-tpl /etc/systemd/system/setup-cluster-dns.service
systemctl enable setup-cluster-dns.service
