#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

cp-tpl /etc/systemd/system/var-lib-home\\x2dcluster.mount
systemctl enable var-lib-home\\x2dcluster.mount
