#!/usr/bin/env bash
# shellcheck source-path=../../../
set -Eeo pipefail; shopt -s inherit_errexit
source "$PKGROOT/lib/common.sh"
set -x

cp-tpl /etc/systemd/network/host.network

mkdir /var/lib/persistent

# https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html#x-systemd.makefs
# The mkfs and growfs options are not available when specifying this mount as a systemd mount unit, so we use fstab
printf "/dev/vdb  /var/lib/persistent   ext4    defaults,x-systemd.makefs,x-systemd.growfs\n" >>/etc/fstab

cp-tpl /etc/systemd/system/link-k3s-data.service
systemctl enable link-k3s-data.service

apt-install linux-image-amd64
