#!/bin/sh
set -e
# Depend on settings so we can check if we are the boot-server
PREREQS="settings"
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

attest=/usr/local/lib/upkg/.upkg/home-cluster/workloads/node/bin/attest
if jq -re '(.["node-label"] // []) | index("node-role.cluster.local/boot-server=true")!=null' /run/initramfs/node-settings.json >/dev/null; then
  log_warning_msg "Skipping remote attestation: This node is the boot-server. Saving attestation quote to /run/initramfs/quote.tar instead."
  $attest generate-quote >/run/initramfs/quote.tar
else
  set +e; configure_networking; set -e
  if [ -n "$ROOTSERVER" ]; then
    if secrets=$($attest attest "http://${ROOTSERVER}/attest"); then
      printf "%s\n" "$secrets" >/run/initramfs/cluster-secrets.json
    else
      log_failure_msg "Remote attestation failed"
    fi
  else
    log_failure_msg "Skipping remote attestation: ROOTSERVER/NEXT_SERVER not found in DHCP lease"
    exit 0
  fi
fi
