#!/bin/sh
set -e
# We don't have any prerequirements
PREREQS=""
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

set +e; configure_networking; set -e
if [ -n "$ROOTSERVER" ]; then
  /usr/local/lib/upkg/.upkg/home-cluster/workloads/node/bin/safeboot-attest "http://${ROOTSERVER}/attest"
else
  log_warning_msg "Skipping cluster authentication: ROOTSERVER/NEXT_SERVER not found in DHCP lease"
  exit 1
fi
