#!/usr/bin/env bash
set -Eeo pipefail; shopt -s inherit_errexit
[[ $1 != prereqs ]] || { echo ""; exit 0; }

PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
# shellcheck source=../common.sh
source "$PKGROOT/common.sh"

main() {
  local boot_path=/run/initramfs/boot
  if [[ -e $boot_path ]]; then
    info "Boot partition mount detected, unmounting"
    umount $boot_path
    rmdir $boot_path
  fi
}

main "$@"
