#!/bin/sh
set -e
# Make sure the settings have been downloaded or copied from the ESP before unmounting
PREREQS="settings"
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck disable=SC1091
. /scripts/functions

esp=/run/initramfs/efi
if [ -e $esp ]; then
  log_success_msg "ESP mount detected, unmounting"
  umount "$esp"
  rm -rf "$esp"
  log_end_msg
fi
