#!/usr/bin/env bash
set -Eeo pipefail; shopt -s inherit_errexit
case $1 in
  # Make sure the node configuration has been downloaded or copied from the boot partition before unmounting
  prereqs) echo "node-config"; exit 0;;
esac

PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
# shellcheck source=../common.sh
source "$PKGROOT/common.sh"

boot=/run/initramfs/boot
if [[ -e $boot ]]; then
  info "Boot partition mount detected, unmounting"
  umount "$boot"
  rm -rf "$boot"
fi
