#!/usr/bin/env bash
set -Eeo pipefail; shopt -s inherit_errexit
[[ $1 != prereqs ]] || { echo ""; exit 0; }

PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
# shellcheck source=../common.sh
source "$PKGROOT/common.sh"

main() {
  boot=/run/initramfs/boot-disk
  if [[ -e $boot ]]; then
    info "Boot partition mount detected, unmounting"
    umount "$boot"
    rm -rf "$boot"
  fi
}

main "$@"
