#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

curl -sfL https://get.k3s.io | \
  INSTALL_K3S_SKIP_START=true \
  K3S_TOKEN=$K3S_TOKEN \
  K3S_URL=$K3S_URL \
  $ROOTCMD sh -

# /etc/rancher/k3s is created on master nodes but not on agents for some reason
mkdir -p "${target:?}/etc/rancher/k3s"

exit $error
