#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

mkdir "${target:?}/var/lib/persistent"

# https://www.freedesktop.org/software/systemd/man/latest/systemd.mount.html#x-systemd.makefs
# The mkfgs and growfs options are not available when specifying this mount as a systemd mount unit, so we use fstab
ainsl /etc/fstab "/dev/vdb  /var/lib/persistent   ext4    defaults,x-systemd.makefs,x-systemd.growfs"

exit $error
