---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-apiserver-client-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-apiserver-client-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-apiserver-client-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-apiserver-client-ca
subjects:
- kind: ServiceAccount
  name: kube-apiserver-client-ca
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-apiserver-client-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: smallstep
      app.kubernetes.io/component: kube-apiserver-client-ca
  ingress:
  - toPorts:
    - ports:
      - port: "9000"
    fromEntities:
    - all
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-client-ca-host
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
  ports:
  - name: api
    port: 9001
    nodePort: 9001
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-client-ca-external
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
  annotations:
    coredns.io/hostname: pki-kube.DOMAIN.
spec:
  type: LoadBalancer
  ipFamilies: [IPv4, IPv6]
  ipFamilyPolicy: RequireDualStack
  selector:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
  ports:
  - name: api
    port: 9001
    targetPort: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-apiserver-client-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: kube-apiserver-client-ca
spec:
  serviceName: kube-apiserver-client-ca
  selector:
    matchLabels:
      app.kubernetes.io/name: smallstep
      app.kubernetes.io/component: kube-apiserver-client-ca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smallstep
        app.kubernetes.io/component: kube-apiserver-client-ca
        cluster.local/allow-apiserver-egress: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: kube-apiserver-client-ca
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: setup-kube-apiserver-client-ca-config
        image: ghcr.io/andsens/phxc-utils
        command: [/home/step/scripts/setup-kube-apiserver-client-ca-config.sh]
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: CLUSTER_DOMAIN
          value: cluster.domain
        - name: CLUSTER_ADMIN_SSH_KEYS
          value: cluster.admin.ssh-keys
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: scripts
          mountPath: /home/step/scripts
        - name: config
          mountPath: /home/step/config-ro
        - name: kube-apiserver-client-ca-cert
          mountPath: /home/step/kube-api-secrets/kube_apiserver_client_ca.crt
          readOnly: true
        - name: kube-apiserver-client-ca-key
          mountPath: /home/step/kube-api-secrets/kube_apiserver_client_ca_key
          readOnly: true
        - name: secrets
          mountPath: /home/step/secrets
        - name: config-rw
          mountPath: /home/step/config
      containers:
      - name: step-ca
        image: cr.step.sm/smallstep/step-ca:0.27.2
        command: [/usr/local/bin/step-ca]
        args: [/home/step/config/ca.json]
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: api
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        volumeMounts:
        - name: secrets
          mountPath: /home/step/secrets
          readOnly: true
        - name: templates
          mountPath: /home/step/templates
        - name: config-rw
          mountPath: /home/step/config
        - name: database
          mountPath: /home/step/db
          readOnly: false
      volumes:
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0755
      - name: config
        configMap:
          name: kube-apiserver-client-ca-config
      - name: templates
        configMap:
          name: kube-apiserver-client-ca-templates
      - name: secrets
        emptyDir:
          medium: Memory
      - name: kube-apiserver-client-ca-cert
        hostPath:
          path: /var/lib/rancher/k3s/server/tls/client-ca.crt
          type: File
      - name: kube-apiserver-client-ca-key
        hostPath:
          path: /var/lib/rancher/k3s/server/tls/client-ca.key
          type: File
      - name: config-rw
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: database
      labels:
        app.kubernetes.io/name: smallstep
        app.kubernetes.io/component: kube-apiserver-client-ca
    spec:
      storageClassName: longhorn
      accessModes: [ReadWriteOnce]
      resources: {requests: {storage: 1Mi}}
