apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smallstep
images:
- name: ghcr.io/andsens/phxc-utils
  newTag: sha-6f1e1cf
resources:
- ../../lib/cluster-settings
- namespace.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml
- https://raw.githubusercontent.com/smallstep/helm-charts/v0.22.0/step-issuer/crds/certmanager.step.sm_stepissuers.yaml
- kube-client-ca.yaml
- kube-server-ca.yaml
- kube-server-issuer.yaml
- node-role.yaml
- Kptfile
- resourcegroup.yaml
configMapGenerator:
- files:
  - scripts/setup-kube-client-ca-config.sh
  - scripts/setup-kube-server-ca-config.sh
  name: scripts
- files:
  - config/templates/admin.tpl
  name: kube-client-ca-templates
- files:
  - config/kube-client-ca.json
  - config/kube-server-ca.json
  name: ca-configs
- files: []
  name: ca-templates
replacements:
- source: {fieldPath: data.domain, kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {kind: Service, name: kube-client-ca-external}
    fieldPaths: [metadata.annotations.coredns\.io/hostname]
    options: {delimiter: '.', index: 1}
  - select: {group: apps, kind: StatefulSet, name: kube-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-client-ca-config].env.[name=CLUSTER_DOMAIN].value"]
- source: {fieldPath: 'data.admin.ssh-keys' , kind: ConfigMap, name: cluster-settings}
  targets:
  - select: {group: apps, kind: StatefulSet, name: kube-client-ca}
    fieldPaths: ["spec.template.spec.initContainers.[name=setup-kube-client-ca-config].env.[name=CLUSTER_ADMIN_SSH_KEYS].value"]
