---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: step-ca-root
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  commonName: Phoenix Cluster Root CA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  isCA: true
  secretName: step-ca-root
  duration: 175200h
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: step-ca-root
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  ca:
    secretName: step-ca-root
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: step-ca-intermediate
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  commonName: Phoenix Cluster Intermediate CA
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: step-ca-root
  secretName: step-ca-intermediate
  duration: 175200h
  isCA: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [get]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
- apiGroups: [""]
  resources: [secrets]
  resourceNames:
  - step-issuer-provisioner
  - step-issuer-provisioner-password
  - ssh-host-provisioner
  - ssh-host-provisioner-password
  - kube-apiserver-client-ca
  verbs: [get, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: step-ca
subjects:
- kind: ServiceAccount
  name: step-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
rules:
- apiGroups: [certmanager.step.sm]
  resources: [stepclusterissuers]
  verbs: [create]
- apiGroups: [certmanager.step.sm]
  resources: [stepclusterissuers]
  resourceNames: [step-issuer]
  verbs: [get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: step-ca
subjects:
- kind: ServiceAccount
  name: step-ca
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: smallstep
      app.kubernetes.io/component: step-ca
  ingress:
  - toPorts:
    - ports:
      - port: "9000"
    fromEntities:
    - all
---
apiVersion: v1
kind: Service
metadata:
  name: step-ca-external
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
  annotations:
    coredns.io/hostname: pki.DOMAIN.
spec:
  type: LoadBalancer
  ipFamilies: [IPv4, IPv6]
  ipFamilyPolicy: RequireDualStack
  selector:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
  ports:
  - name: api
    port: 9000
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
  ports:
  - name: api
    port: 9000
    targetPort: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: step-ca
  labels:
    app.kubernetes.io/name: smallstep
    app.kubernetes.io/component: step-ca
spec:
  serviceName: step-ca
  selector:
    matchLabels:
      app.kubernetes.io/name: smallstep
      app.kubernetes.io/component: step-ca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smallstep
        app.kubernetes.io/component: step-ca
        cluster.local/allow-apiserver-egress: "true"
    spec:
      serviceAccountName: step-ca
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: setup-step-ca-config
        image: ghcr.io/andsens/phxc-utils
        command: [/home/step/scripts/setup-step-ca-config.sh]
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: CLUSTER_DOMAIN
          value: cluster.domain
        volumeMounts:
        - name: root
          mountPath: /home/step/certs/root_ca.crt
          subPath: tls.crt
        - name: scripts
          mountPath: /home/step/scripts
        - name: config
          mountPath: /home/step/config-ro
        - name: config-rw
          mountPath: /home/step/config
        - name: provisioner-secrets
          mountPath: /home/step/provisioner-secrets
      containers:
      - name: step-ca
        image: cr.step.sm/smallstep/step-ca:0.27.2
        command: [/usr/local/bin/step-ca]
        args: [/home/step/config/ca.json]
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: api
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        volumeMounts:
        - name: root
          mountPath: /home/step/certs/root_ca.crt
          subPath: tls.crt
        - name: intermediate
          mountPath: /home/step/certs/intermediate_ca.crt
          subPath: tls.crt
        - name: intermediate
          mountPath: /home/step/secrets/intermediate_ca_key
          subPath: tls.key
        - name: config-rw
          mountPath: /home/step/config
        - name: provisioner-secrets
          mountPath: /home/step/provisioner-secrets
        - name: database
          mountPath: /home/step/db
      volumes:
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0755
      - name: config
        configMap:
          name: ca-config
      - name: provisioner-secrets
        emptyDir:
          medium: Memory
      - name: root
        secret:
          secretName: step-ca-root
      - name: intermediate
        secret:
          secretName: step-ca-intermediate
      - name: config-rw
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: database
      labels:
        app.kubernetes.io/name: smallstep
        app.kubernetes.io/component: step-ca
    spec:
      storageClassName: longhorn
      accessModes: [ReadWriteOnce]
      resources: {requests: {storage: 1Mi}}
