#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -SM /etc/systemd/system/bootstrap.service
$ROOTCMD systemctl enable bootstrap.service

$ROOTCMD fai-mk-configspace

exit $error
