#!/usr/bin/env bash
# shellcheck source-path=../..
set -Eeo pipefail; shopt -s inherit_errexit
PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../..")

main() {
  source "$PKGROOT/lib/common.sh"
  source "$PKGROOT/lib/vm.sh"

  DOC="update-machines - Update and reboot machines with the new disk images
Usage:
  update-machines [MACHINE...]
"
# docopt parser below, refresh this parser with `docopt.sh update-machines`
# shellcheck disable=2016,2086,2317,1090,1091,2034,2154
docopt() { source "$PKGROOT/.upkg/docopt-lib.sh/docopt-lib.sh" '2.0.0a3' || {
ret=$?;printf -- "exit %d\n" "$ret";exit "$ret";};set -e
trimmed_doc=${DOC:0:107};usage=${DOC:70:37};digest=5cf82;options=();node_0(){
value MACHINE a true;};node_1(){ repeatable 0;};node_2(){ optional 1;};cat \
<<<' docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" >&2;printf "%s\n" \
"${DOC:70:37}" >&2;exit 1;}';local varnames=(MACHINE) varname;for varname in \
"${varnames[@]}"; do unset "var_$varname";done;parse 2 "$@";local \
p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
done;if declare -p var_MACHINE >/dev/null 2>&1; then eval $p'MACHINE=("${var_M'\
'ACHINE[@]}")';else eval $p'MACHINE=()';fi;eval ;local docopt_i=1;[[ \
$BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for ((;docopt_i>0;docopt_i--)); do for \
varname in "${varnames[@]}"; do declare -p "$p$varname";done;done;}
# docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib.sh/docopt-lib.sh"' update-machines`
  eval "$(docopt "$@")"

  log_forward_to_journald true

  local bootstrapper_vm
  bootstrapper_vm=$(get_setting "machines.bootstrapper.vm")

  cache_all_vms

  if [[ ${#MACHINE[@]} -eq 0 ]]; then
    info "No machines specified, choosing all"
    readarray -d $'\n' MACHINE < <(yq -r '.machines | to_entries[] | select(.key != "truenas" and .key != "workstation") | .key' "$PKGROOT/home-cluster.yaml")
  fi

  # shellcheck disable=2153
  printf -- '#!/usr/bin/env bash\nMACHINE=(%s)\n' "${MACHINE[*]}" > "$PKGROOT/bootstrap.args.sh"
  # shellcheck disable=2064
  trap "rm -f \"$PKGROOT/bootstrap.args.sh\"" EXIT

  # shellcheck disable=2154
  start_vm "$bootstrapper_vm"
  # shellcheck disable=2064
  trap "rm -f \"$PKGROOT/bootstrap.args.sh\"; stop_vm \"$bootstrapper_vm\"" EXIT

  info "Waiting for bootstrapping to complete"
  while [[ -e "$PKGROOT/bootstrap.args.sh" ]]; do
    sleep 1
  done
  info "Bootstrapping completed"
  stop_vm "$bootstrapper_vm"
  trap "" EXIT

  local machine diskpath ret=0 latest_imgpath current_imgpath
  for machine in "${MACHINE[@]}"; do
    vmname=$(get_setting "machines[\"$machine\"].vm")
    diskpath=$(get_setting "machines[\"$machine\"].disk")

    latest_imgpath="$PKGROOT/images/$machine.raw"
    current_imgpath="$PKGROOT/images/$machine.current.raw"
    if [[ -e "$latest_imgpath" ]]; then
      info "Image for '%s' found, replacing disk and then renaming to '%s'" "$vmname" "$current_imgpath"
      local res=0
      replace_vm_disk "$vmname" "$latest_imgpath" "$diskpath" || res=$?
      if [[ $res = 0 ]]; then
        info "Successfully replaced disk for '%s', renaming image to .current.raw" "$vmname"
        mv "$latest_imgpath" "$current_imgpath"
      else
        error "Failed to replace disk for '%s'" "$vmname"
        ret=$res
      fi
    else
      error "Image for '%s' not found, '%s' failed to create an image" "$vmname" "$bootstrapper_vm"
      ret=1
    fi
  done
  if [[ $ret = 0 ]]; then
    info "Successfully replaced the disks on all of the specified VMs"
  else
    error "Failed to replace the disks on some VMs"
  fi
  return $ret
}

main "$@"
