#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -SM /etc/systemd/system/link-k3s-data.service
$ROOTCMD systemctl enable link-k3s-data.service

exit $error
