#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
(
  set -e
  cd "${target:?}/tmp"
  curl -sL --fail --remote-name-all "https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${arch_suffix:?}.tar.gz"{,.sha256sum}
  sha256sum --check "cilium-linux-$arch_suffix.tar.gz.sha256sum"
  tar xzvfC "cilium-linux-$arch_suffix.tar.gz" "${target:?}/usr/local/bin"
  rm "cilium-linux-$arch_suffix.tar.gz"{,.sha256sum}
)
fcopy -SM /etc/systemd/system/install-cilium.service
$ROOTCMD systemctl enable install-cilium.service

exit $error
