#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -SM /etc/systemd/system/apply-manifests.service
$ROOTCMD systemctl enable apply-manifests.service

exit $error
