#!/usr/bin/env bash
set -eo pipefail; shopt -s inherit_errexit

# shellcheck source=../../../../../../../.upkg/orbit-online/records.sh/records.sh
source "/usr/local/lib/upkg/orbit-online/records.sh/records.sh"

main() {
  DOC="install-cilium - Install cilium in k3s
Usage:
  install-cilium CLUSTER_IPV4_CIDR CLUSTER_IPV6_CIDR
"
# docopt parser below, refresh this parser with `docopt.sh K8SMASTER`
# shellcheck disable=2016,1090,1091,2034
docopt() {
source "/usr/local/lib/upkg/andsens/docopt.sh/docopt-lib.sh" '1.0.0' || { ret=$?
printf -- "exit %d\n" "$ret"; exit "$ret"; }; set -e; trimmed_doc=${DOC:0:98}
usage=${DOC:39:59}; digest=fd5a5; shorts=(); longs=(); argcounts=(); node_0(){
value CLUSTER_IPV4_CIDR a; }; node_1(){ value CLUSTER_IPV6_CIDR a; }; node_2(){
required 0 1; }; node_3(){ required 2; }; cat <<<' docopt_exit() {
[[ -n $1 ]] && printf "%s\n" "$1" >&2; printf "%s\n" "${DOC:39:59}" >&2; exit 1
}'; unset var_CLUSTER_IPV4_CIDR var_CLUSTER_IPV6_CIDR; parse 3 "$@"
local prefix=${DOCOPT_PREFIX:-''}; unset "${prefix}CLUSTER_IPV4_CIDR" \
"${prefix}CLUSTER_IPV6_CIDR"
eval "${prefix}"'CLUSTER_IPV4_CIDR=${var_CLUSTER_IPV4_CIDR:-}'
eval "${prefix}"'CLUSTER_IPV6_CIDR=${var_CLUSTER_IPV6_CIDR:-}'; local docopt_i=1
[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2; for ((;docopt_i>0;docopt_i--)); do
declare -p "${prefix}CLUSTER_IPV4_CIDR" "${prefix}CLUSTER_IPV6_CIDR"; done; }
# docopt parser above, complete command for generating this parser is `docopt.sh --library='"/usr/local/lib/upkg/andsens/docopt.sh/docopt-lib.sh"' K8SMASTER`
  eval "$(docopt "$@")"

  local notified=false max_wait=300 wait_left=300
  while ! kubectl get -n kube-system deployment coredns -o name >/dev/null 2>&1; do
    $notified || info "k3s is not ready yet..."
    notified=true
    sleep 1
    ((--wait_left > 0)) || fatal "Timed out after %d seconds for cilium to become ready." "$((max_wait / 60))"
  done
  if ! kubectl get -n kube-system deployment cilium-operator -o name >/dev/null 2>&1; then
    info "Cilium is not installed, installing now"
    exec /usr/local/bin/cilium install --version=1.15.1 \
      --set=ipam.operator.clusterPoolIPv4PodCIDRList="$CLUSTER_IPV4_CIDR" \
      --set=ipam.operator.clusterPoolIPv6PodCIDRList="$CLUSTER_IPV6_CIDR" \
      --set=ipv6.enabled=true \
      --set=envoy.enabled=false \
      --set=hubble.enabled=false \
      --set=hubble.relay.gops.enabled=false \
      --set=kubeProxyReplacement=true \
      --set=encryption.enabled=true \
      --set=encryption.type=wireguard \
      --set=socketLB.enabled=true \
      --set=kubeConfigPath=/etc/rancher/k3s/k3s.yaml
  else
    info "Cilium already installed, nothing to do"
  fi
}

main "$@"
