#!/usr/bin/env bash
set -eo pipefail; shopt -s inherit_errexit

# shellcheck source=../../../../../../../.upkg/orbit-online/records.sh/records.sh
source "/usr/local/lib/upkg/orbit-online/records.sh/records.sh"

notified=false
max_wait=300
wait_left=$max_wait
while ! kubectl get -n kube-system deployment coredns -o name >/dev/null 2>&1; do
  $notified || info "k3s is not ready yet..."
  notified=true
  sleep 1
  ((--wait_left > 0)) || fatal "Timed out after %d seconds for cilium to become ready." "$((max_wait / 60))"
done
if ! kubectl get -n kube-system deployment cilium-operator -o name >/dev/null 2>&1; then
  info "Cilium is not installed, installing now"
  exec /usr/local/bin/cilium install --version=1.15.1 \
    --set=ipam.operator.clusterPoolIPv4PodCIDRList="{%CLUSTER_IP4_CIDR%}" \
    --set=ipam.operator.clusterPoolIPv6PodCIDRList="{%CLUSTER_IP6_CIDR%}" \
    --set=ipv6.enabled=true \
    --set=envoy.enabled=false \
    --set=hubble.enabled=false \
    --set=hubble.relay.gops.enabled=false \
    --set=kubeProxyReplacement=true \
    --set=encryption.enabled=true \
    --set=encryption.type=wireguard \
    --set=socketLB.enabled=true \
    --set=kubeConfigPath=/etc/rancher/k3s/k3s.yaml
else
  info "Cilium already installed, nothing to do"
fi
