name: Build disk-utils image

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
    paths:
    - .github/workflows/build-disk-utils.yaml
    - .github/assets/disk-utils.Dockerfile

env:
  ALPINE_VERSION: '3.21'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Compute metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/andsens/phxc-disk-utils
        tags: type=sha
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: lib/common-context
        file: .github/assets/disk-utils.Dockerfile
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        build-args: |
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: |
          org.opencontainers.image.description="Image for running the disk-utils script, which converts a container image to bootable disk image"
