#!/usr/bin/env bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -Mv /etc/hostname || echo $HOSTNAME > $target/etc/hostname

$ROOTCMD systemd-machine-id-setup

fai-link /etc/mtab ../proc/self/mounts

exit $error
