#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD usermod -L root
# enable sudo for admin
ainsl /etc/sudoers "${ADMIN_USERNAME:?}   ALL = ALL"
[ -f "$target/usr/bin/sudo" ] || echo "WARNING. Package sudo is not installed"
$ROOTCMD useradd -m -s /bin/bash "$ADMIN_USERNAME"
$ROOTCMD usermod -p "${ADMIN_PASSWORD:?}" "$ADMIN_USERNAME"
userdir=$($ROOTCMD getent passwd "$ADMIN_USERNAME" | cut -d: -f6 )
$ROOTCMD mkdir "$userdir/.ssh"
[[ -z $ADMIN_AUTH_KEYS ]] || ainsl -a "$userdir/.ssh/authorized_keys" "$ADMIN_AUTH_KEYS"
$ROOTCMD chown -R "$ADMIN_USERNAME:$ADMIN_USERNAME" "$userdir/.ssh"
$ROOTCMD chmod -R u=rwX,go=rX "$userdir/.ssh"

exit $error
